### ISSUE TITLE
Year + Quarter repeats even if week only crosses a month

### ISSUE THREAD

**Issue by PhyberApex** [ljavuras/obsidian-power-tools#1]
Hey really like this one! One minor thing. Is it on purpose that you output the year and quarter everytime a week crosses a boundary of a month? Because e.g. the week that starts in January and ends in February does neither cross years nor quarters and so this would just repeat the same quarter and year. I can create a PR if you want to address this. Already did while copying your work into my vault :)

**Comment by ljavuras** [comment]
Yes, this is on purpose.

I tried to keep it as simple as possible because I want people to be able to adopt it,  even with little experience in programming.

That said, I'm very interested in your solution, do you think you can push the patch for weekly template's `YYYY / [Q]Q / MMMM` line?

Feel free to include a readme for brief instruction, as well as a credit to yourself:)

**Comment by PhyberApex** [comment]
Sure thing, there you go! https://github.com/ljavuras/obsidian-periodic-notes-template-navigation/pull/2

~Cheers
